### ISSUE TITLE
SPM  error while adding

### ISSUE THREAD

**Issue by YurchukV** [EmilioPelaez/ScrollingPageControl#3]
Showing All Messages
: https://github.com/EmilioPelaez/ScrollingPageControl.git has no Package.swift manifest for version 0.1.1
<img width="736" alt="Снимок экрана 2020-08-27 в 00 04 58" src="https://user-images.githubusercontent.com/6242240/91340006-185f6780-e7f9-11ea-99c1-60dece255d3e.png">

**Comment by EmilioPelaez** [comment]
Thanks for the heads up, I'll take a look at it!

**Comment by EmilioPelaez** [comment]
Fixed on 0.1.2 release
