### ISSUE TITLE
not center

### ISSUE THREAD

**Issue by tallot13** [EmilioPelaez/ScrollingPageControl#5]
from example project, size 8 and size 2, constraint not changed(center)
<img width="336" alt="Снимок экрана 2021-03-18 в 13 39 14" src="https://user-images.githubusercontent.com/48832276/111613322-71bbd200-87ef-11eb-899f-7e6da8baf408.png">
<img width="341" alt="Снимок экрана 2021-03-18 в 13 38 39" src="https://user-images.githubusercontent.com/48832276/111613332-741e2c00-87ef-11eb-9aee-1cfbaf45427c.png">m

_Originally posted by @tallot13 in https://github.com/EmilioPelaez/ScrollingPageControl/issues/4#issuecomment-801817425_

**Comment by tallot13** [comment]
if set maxDots to two will fine, not sync values pages, maxDots

**Comment by EmilioPelaez** [comment]
@tallot13 could you please provide a sample project where this can be seen?

**Comment by tallot13** [comment]
sample project in this repo

**Comment by tallot13** [comment]
change line 	let pages: Int = 2

**Comment by tallot13** [comment]
https://github.com/EmilioPelaez/ScrollingPageControl/blob/master/Example/ScrollingPageControl/TestViewController.swift#L17

**Comment by EmilioPelaez** [comment]
Thanks @tallot13. I don't have the time to fix it right now, I'll get to it eventually. If you want to take a shot at it, feel free to open a PR.

**Comment by EmilioPelaez** [comment]
This should be fixed on 1.0.0. Please let me know if you see any other issues.
